# Travis CI configuration file.

dist: trusty

sudo: false

language: php

php:
    - 7.1

before_install: phpenv config-rm xdebug.ini

script:
    - ./phpunit --color=auto test/HolaMundoTest.php 

notifications:
    email: false

